-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 17:05:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VGDB_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VGDB_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VGDB_db` DEFAULT CHARACTER SET utf8 ;
USE `VGDB_db` ;

-- -----------------------------------------------------
-- Table `VGDB_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `VGDB_db`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idSerie_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `idGenero_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `score_critics` DECIMAL NOT NULL,
  `genres_id` INT NOT NULL,
  `series_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `idJogo_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_games_series1_idx` (`series_id` ASC) VISIBLE,
  INDEX `fk_games_genres1_idx` (`genres_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `VGDB_db`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `VGDB_db`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `number_employees` INT NULL,
  `website` VARCHAR(60) NULL,
  `foundation_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`generations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`generations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `name` VARCHAR(60) NULL,
  `date_init` DATETIME NOT NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idGeracao_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`platforms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `price` DECIMAL NOT NULL,
  `launch_date` DATE NULL,
  `manufacturer` VARCHAR(60) NULL,
  `units_sold` INT NULL,
  `generations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idConsole_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_consoles_generations1_idx` (`generations_id` ASC) VISIBLE,
  CONSTRAINT `fk_consoles_generations1`
    FOREIGN KEY (`generations_id`)
    REFERENCES `VGDB_db`.`generations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`developers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `ocupation` VARCHAR(100) NOT NULL,
  `nacionality` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProletario_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`releases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`releases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `consoles_generations_id1` INT NOT NULL,
  `games_id` INT NOT NULL,
  `platforms_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idLancamento_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_launches_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_launches_platforms1_idx` (`platforms_id` ASC) VISIBLE,
  CONSTRAINT `fk_launches_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_db`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_launches_platforms1`
    FOREIGN KEY (`platforms_id`)
    REFERENCES `VGDB_db`.`platforms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` DECIMAL NOT NULL,
  `description` LONGTEXT NOT NULL,
  `games_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_reviews_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_db`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `VGDB_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`companies_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`companies_has_games` (
  `companies_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  PRIMARY KEY (`companies_id`, `games_id`),
  INDEX `fk_companies_has_games_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_companies_has_games_companies1_idx` (`companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_companies_has_games_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `VGDB_db`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_db`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`users_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`users_has_games` (
  `users_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `games_id`),
  INDEX `fk_users_has_games_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_users_has_games_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_games_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `VGDB_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_db`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_db`.`games_has_developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_db`.`games_has_developers` (
  `games_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`games_id`, `developers_id`),
  INDEX `fk_games_has_developers_developers1_idx` (`developers_id` ASC) VISIBLE,
  INDEX `fk_games_has_developers_games1_idx` (`games_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_has_developers_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_db`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `VGDB_db`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
