-- MySQL Script generated by MySQL Workbench
-- Wed Jul  3 15:26:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VGDB_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VGDB_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VGDB_bd` DEFAULT CHARACTER SET utf8 ;
USE `VGDB_bd` ;

-- -----------------------------------------------------
-- Table `VGDB_bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `VGDB_bd`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idSerie_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `idGenero_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `score_critics` DECIMAL NOT NULL,
  `genres_id` INT NOT NULL,
  `series_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `idJogo_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_games_series1_idx` (`series_id` ASC) VISIBLE,
  INDEX `fk_games_genres1_idx` (`genres_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `VGDB_bd`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `VGDB_bd`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `number_employees` INT NULL,
  `website` VARCHAR(60) NULL,
  `foundation_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`generations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`generations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `date_init` DATETIME NOT NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idGeracao_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`platforms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `price` DECIMAL NOT NULL,
  `launch_date` DATE NULL,
  `manufacturer` VARCHAR(80) NULL,
  `units_sold` INT NULL,
  `generations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idConsole_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_consoles_generations1_idx` (`generations_id` ASC) VISIBLE,
  CONSTRAINT `fk_consoles_generations1`
    FOREIGN KEY (`generations_id`)
    REFERENCES `VGDB_bd`.`generations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`developers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `ocupation` VARCHAR(100) NOT NULL,
  `nacionality` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProletario_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`releases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`releases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `games_id` INT NOT NULL,
  `platforms_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idLancamento_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_launches_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_launches_platforms1_idx` (`platforms_id` ASC) VISIBLE,
  CONSTRAINT `fk_launches_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_bd`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_launches_platforms1`
    FOREIGN KEY (`platforms_id`)
    REFERENCES `VGDB_bd`.`platforms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` DECIMAL NOT NULL,
  `description` LONGTEXT NOT NULL,
  `games_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_reviews_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_bd`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `VGDB_bd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`companies_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`companies_has_games` (
  `companies_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  PRIMARY KEY (`companies_id`, `games_id`),
  INDEX `fk_companies_has_games_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_companies_has_games_companies1_idx` (`companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_companies_has_games_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `VGDB_bd`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_bd`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`users_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`users_has_games` (
  `users_id` INT NOT NULL,
  `games_id` INT NOT NULL,
  `hours_played` INT NULL,
  PRIMARY KEY (`users_id`, `games_id`),
  INDEX `fk_users_has_games_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_users_has_games_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_games_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `VGDB_bd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_bd`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`games_has_developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`games_has_developers` (
  `games_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`games_id`, `developers_id`),
  INDEX `fk_games_has_developers_developers1_idx` (`developers_id` ASC) VISIBLE,
  INDEX `fk_games_has_developers_games1_idx` (`games_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_has_developers_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `VGDB_bd`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `VGDB_bd`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `VGDB_bd` ;

-- -----------------------------------------------------
-- Placeholder table for view `VGDB_bd`.`most_sold_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`most_sold_platform` (`id` INT, `name` INT, `units_sold` INT);

-- -----------------------------------------------------
-- Placeholder table for view `VGDB_bd`.`dev_by_ocupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`dev_by_ocupation` (`id` INT, `name` INT, `ocupation` INT);

-- -----------------------------------------------------
-- Placeholder table for view `VGDB_bd`.`company_age`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`company_age` (`id` INT, `name` INT, `age` INT);

-- -----------------------------------------------------
-- Placeholder table for view `VGDB_bd`.`best_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`best_game` (`id` INT, `name` INT, `score_critics` INT);

-- -----------------------------------------------------
-- View `VGDB_bd`.`most_sold_platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VGDB_bd`.`most_sold_platform`;
USE `VGDB_bd`;
CREATE  OR REPLACE VIEW `most_sold_platform` AS
	SELECT 
		id, name, units_sold 
	FROM platforms 
	ORDER BY units_sold DESC LIMIT 10;

-- -----------------------------------------------------
-- View `VGDB_bd`.`dev_by_ocupation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VGDB_bd`.`dev_by_ocupation`;
USE `VGDB_bd`;
CREATE  OR REPLACE VIEW `dev_by_ocupation` AS
	SELECT 
		id, name, ocupation 
	FROM developer 
	ORDER BY ocupation DESC LIMIT 100;

-- -----------------------------------------------------
-- View `VGDB_bd`.`company_age`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VGDB_bd`.`company_age`;
USE `VGDB_bd`;
CREATE  OR REPLACE VIEW `company_age` AS
	SELECT
		id, name, YEAR(NOW()) - YEAR(fundation_date) as age
	FROM companies
	ORDER BY name DESC LIMIT 50;

-- -----------------------------------------------------
-- View `VGDB_bd`.`best_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VGDB_bd`.`best_game`;
USE `VGDB_bd`;
CREATE  OR REPLACE VIEW `best_game` AS
	SELECT
		id, name, score_critics
	FROM games
	ORDER BY score_critics DESC LIMIT 50;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
