-- MySQL Script generated by MySQL Workbench
-- Mon Jul  1 20:29:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VGDB_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VGDB_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VGDB_bd` DEFAULT CHARACTER SET utf8 ;
USE `VGDB_bd` ;

-- -----------------------------------------------------
-- Table `VGDB_bd`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Nickname` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Launches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Launches` (
  `idLancamento` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLancamento`),
  UNIQUE INDEX `idLancamento_UNIQUE` (`idLancamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Genres` (
  `idGenres` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenres`),
  UNIQUE INDEX `nome_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `idGenero_UNIQUE` (`idGenres` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Series` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSerie`),
  UNIQUE INDEX `idSerie_UNIQUE` (`idSerie` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Games` (
  `idGames` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Serie_idSerie` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  `Lancamento_idLancamento` INT NOT NULL,
  `Score_Critica` INT NOT NULL,
  `Score_Publica` INT NOT NULL,
  `Genero_idGenero1` INT NOT NULL,
  `Serie_idSerie1` INT NOT NULL,
  PRIMARY KEY (`idGames`, `Serie_idSerie`, `Genero_idGenero`),
  UNIQUE INDEX `nome_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `idJogo_UNIQUE` (`idGames` ASC) VISIBLE,
  INDEX `fk_Jogo_Lancamento1_idx` (`Lancamento_idLancamento` ASC) VISIBLE,
  INDEX `fk_Jogo_Genero1_idx` (`Genero_idGenero1` ASC) VISIBLE,
  INDEX `fk_Jogo_Serie1_idx` (`Serie_idSerie1` ASC) VISIBLE,
  CONSTRAINT `fk_Jogo_Lancamento1`
    FOREIGN KEY (`Lancamento_idLancamento`)
    REFERENCES `VGDB_bd`.`Launches` (`idLancamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_Genero1`
    FOREIGN KEY (`Genero_idGenero1`)
    REFERENCES `VGDB_bd`.`Genres` (`idGenres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_Serie1`
    FOREIGN KEY (`Serie_idSerie1`)
    REFERENCES `VGDB_bd`.`Series` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Companies` (
  `idCompanies` INT NOT NULL AUTO_INCREMENT,
  `nome_social` VARCHAR(45) NOT NULL,
  `HQ_adress` VARCHAR(45) NOT NULL,
  `No_employers` INT NOT NULL,
  `Website` VARCHAR(45) NULL,
  `Foundation_date` DATE NULL,
  PRIMARY KEY (`idCompanies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Generations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Generations` (
  `idGeracao` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `Date_init` DATETIME NOT NULL,
  `Date_end` DATETIME NULL,
  PRIMARY KEY (`idGeracao`),
  UNIQUE INDEX `idGeracao_UNIQUE` (`idGeracao` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Consoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Consoles` (
  `idConsoles` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Developer` VARCHAR(45) NOT NULL,
  `Starting_price` INT NULL,
  `Units_sold` INT NULL,
  `Lancamento_idLancamento` INT NOT NULL,
  `Geracao_idGeracao` INT NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idConsoles`),
  UNIQUE INDEX `idConsole_UNIQUE` (`idConsoles` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_Console_Lancamento1_idx` (`Lancamento_idLancamento` ASC) VISIBLE,
  INDEX `fk_Console_Geracao1_idx` (`Geracao_idGeracao` ASC) VISIBLE,
  INDEX `fk_Console_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Console_Lancamento1`
    FOREIGN KEY (`Lancamento_idLancamento`)
    REFERENCES `VGDB_bd`.`Launches` (`idLancamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Console_Geracao1`
    FOREIGN KEY (`Geracao_idGeracao`)
    REFERENCES `VGDB_bd`.`Generations` (`idGeracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Console_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `VGDB_bd`.`Companies` (`idCompanies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`developers` (
  `idDevelopers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Birthday` DATETIME NULL,
  `Ocupation` VARCHAR(45) NULL,
  `Birthplace` VARCHAR(45) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idDevelopers`),
  UNIQUE INDEX `idProletario_UNIQUE` (`idDevelopers` ASC) VISIBLE,
  INDEX `fk_Proletario_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Proletario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `VGDB_bd`.`Companies` (`idCompanies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Jogo_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Jogo_has_Usuario` (
  `Jogo_idJogo` INT NOT NULL,
  `Jogo_Serie_idSerie` INT NOT NULL,
  `Jogo_Genero_idGenero` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Jogo_idJogo`, `Jogo_Serie_idSerie`, `Jogo_Genero_idGenero`, `Usuario_idUsuario`),
  INDEX `fk_Jogo_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Jogo_has_Usuario_Jogo1_idx` (`Jogo_idJogo` ASC, `Jogo_Serie_idSerie` ASC, `Jogo_Genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Jogo_has_Usuario_Jogo1`
    FOREIGN KEY (`Jogo_idJogo` , `Jogo_Serie_idSerie` , `Jogo_Genero_idGenero`)
    REFERENCES `VGDB_bd`.`Games` (`idGames` , `Serie_idSerie` , `Genero_idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VGDB_bd`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Reviews` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `Score` DECIMAL NOT NULL,
  `Text` LONGTEXT NULL,
  `Jogo_idJogo` INT NOT NULL,
  `Jogo_Serie_idSerie` INT NOT NULL,
  `Jogo_Genero_idGenero` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idReview`),
  INDEX `fk_Avaliação_Jogo1_idx` (`Jogo_idJogo` ASC, `Jogo_Serie_idSerie` ASC, `Jogo_Genero_idGenero` ASC) VISIBLE,
  INDEX `fk_Avaliação_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliação_Jogo1`
    FOREIGN KEY (`Jogo_idJogo` , `Jogo_Serie_idSerie` , `Jogo_Genero_idGenero`)
    REFERENCES `VGDB_bd`.`Games` (`idGames` , `Serie_idSerie` , `Genero_idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliação_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VGDB_bd`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VGDB_bd`.`Empresa_has_Jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VGDB_bd`.`Empresa_has_Jogo` (
  `Empresa_idEmpresa` INT NOT NULL,
  `Jogo_idJogo` INT NOT NULL,
  `Jogo_Serie_idSerie` INT NOT NULL,
  `Jogo_Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`Empresa_idEmpresa`, `Jogo_idJogo`, `Jogo_Serie_idSerie`, `Jogo_Genero_idGenero`),
  INDEX `fk_Empresa_has_Jogo_Jogo1_idx` (`Jogo_idJogo` ASC, `Jogo_Serie_idSerie` ASC, `Jogo_Genero_idGenero` ASC) VISIBLE,
  INDEX `fk_Empresa_has_Jogo_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_has_Jogo_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `VGDB_bd`.`Companies` (`idCompanies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresa_has_Jogo_Jogo1`
    FOREIGN KEY (`Jogo_idJogo` , `Jogo_Serie_idSerie` , `Jogo_Genero_idGenero`)
    REFERENCES `VGDB_bd`.`Games` (`idGames` , `Serie_idSerie` , `Genero_idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
